### ISSUE TITLE
Unable to install pandas in docker image fail

### ISSUE THREAD

**Issue by cena7** [datamechanics/examples#7]
Thanks for your docker images.
I tried using and i want to install `pandas` in my docker image ( not `pyspark.pands`). It catastrophically fail.
Any advice or resolution highly appricated

my docker file

```
FROM datamechanics/spark:3.2.0-hadoop-3.3.1-java-11-scala-2.12-python-3.8-latest

ENV PYSPARK_MAJOR_PYTHON_VERSION=3

WORKDIR /opt/application/

RUN pip install pandas

# Copy file
COPY main.py .
```
Error i get:
```

` pandas/_libs/groupby.pyx:823:0: Referring to a memoryview typed argument directly in a nested closure function is not supported in Cython 0.x. Either upgrade to Cython 3, or assign the argument to a local variable and use that in the nested function.`


.....

24     Traceback (most recent call last):
#8 63.24       File "<string>", line 1, in <module>
#8 63.24       File "/tmp/pip-install-p0utzbpj/pandas/setup.py", line 651, in <module>
#8 63.24         ext_modules=maybe_cythonize(extensions, compiler_directives=directives),
#8 63.24       File "/tmp/pip-install-p0utzbpj/pandas/setup.py", line 424, in maybe_cythonize
#8 63.24         return cythonize(extensions, *args, **kwargs)
#8 63.24       File "/tmp/pip-build-env-1il8nzwz/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1118, in cythonize
#8 63.24         result.get(99999)  # seconds
#8 63.24       File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
#8 63.24         raise self._value
#8 63.24     Cython.Compiler.Errors.CompileError: pandas/_libs/groupby.pyx
```

**Comment by ashishmgofficial** [comment]
I got the same issue and ran the steps as root:

`USER 0`

I also updated pip prior to any installations using

`RUN pip3 install --upgrade pip setuptools wheel build`

**Comment by cena7** [comment]
> @cena7 I got the same issue and ran the steps as root:
> 
> `USER 0`
> 
> I also updated pip prior to any installations using
> 
> `RUN pip3 install --upgrade pip setuptools wheel build`

@ashishmgofficial  what is the default user id you used after install
